### ISSUE TITLE
Build a scaled batch processing infrastructure with SQS and ECS

### ISSUE THREAD

**Issue by iansltx** [covie-interviews/ShinyButtons#1]
# TODO: A more detailed spec

**NOTE:** You'll need your own AWS account for this. Use GitHub Actions for any CI you need to do, Terraform or CloudFormation for Infrastructure as Code. When you get to the point that GitHub won't let you access the things you'll need to access, let me know and I'll bump you up to Maintainer permissions on this repo.

- [ ] Set up a container that pulls stuff off of an SQS queue, processes it (can just be "wait the number of seconds the job tells me to wait), report back to SQS that the job is complete, and spit out logs in the process. What's entertaining is "block for X seconds" is not terribly far off from our actual workload in terms of compute requirements.
- [ ] Set up an ECS-on-EC2 cluster running the containers built above. Start with one or two ECS tasks running on one box. Use a c6g.medium instance type. This will mean you'll need to push both Arm and x86 versions of whatever app-level image you're working with, because Fargate needs x86 and c6g's are Arm.
- [ ] Set up a scheduled ECS task on Fargate that, on a cron (this is built into ECS), loads a bunch (say, 10k) of jobs into SQS. The task definitions can be almost-trivial (e.g. number of seconds to wait on the worker side before considering the job done). 
- [ ] That same task should then scale both instances and tasks-within-instance up on the ECS side so the jobs get done quicker. Scale-up should use Spot Instances to save money. Scale to 3-4 boxes wide, with 50 tasks per box.
- [ ] Once tasks are queued and scale-up happens, exit that cron'd control task.
- [ ] Once the workers chew through all jobs, such that the SQS queue has had zero jobs pending etc. for 5-10 minutes, scale ECS back down to where it was before. I *think* CloudWatch can watch for this and fire off events, which can feed into Lambda, to do this.

**Comment by ShinyButtons** [comment]
Task complete

**Comment by ShinyButtons** [comment]
Task complete
